let handler  = async (m, { conn }) => {
  conn.reply(m.chat,`“${pickRandom(global.bucin)}”`, m)
}
handler.command = /^(frases|frase|fra)$/i
handler.help = ['frases']
handler.tags = ['data']
handler.owner = false
handler.mods = false
handler.limit = true
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null

module.exports = handler

function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())]
}

// https://jalantikus.com/tips/kata-kata-bucin/
global.bucin = [
  'Elijo estar solo, no porque esté esperando al perfecto, sino porque necesito a alguien que nunca se rinda',
  'Se crea una sola persona con una pareja que aún no ha encontrado',
  'Solteros. Tal vez sea la forma de Dios de decir Descansa del amor equivocado',
  'Los solteros son jóvenes que priorizan su desarrollo personal para un amor con más clase en el futuro',
  'No busco a alguien que sea perfecto, sino a alguien que se vuelva perfecto gracias a mis fortalezas',
  'Los novios de la gente son nuestras almas gemelas pendientes',
  'Los solteros deben pasar. Todo tiene un tiempo, cuando toda soledad se convierte en unión con un amante halal. Ten paciencia.',
  'Romeo estaba dispuesto a morir por Julieta, Jack murió para salvar a Rose. El caso es que, si quieres vivir, sé soltero',
  'Busco personas no por sus fortalezas sino por su sinceridad',
  'Madmates no son chanclas, que a menudo se confunden. Así que continúe en la lucha adecuada',
  'Si te conviertes en las cuerdas de la guitarra, yo no quiero ser el guitarrista. Porque no quiero dejarte',
  'Si amarte es una ilusión, déjame imaginar para siempre',
  'Cariño ... Mi trabajo es solo amarte, no luchar contra el destino',
  'Cuando estoy contigo, parece que 1 hora es solo 1 segundo, pero cuando estoy lejos de ti, parece que 1 día se convierte en 1 año',
  'Los plátanos Kolak saben sumedang, aunque la distancia se extienda, mi amor nunca desaparecerá',
  'Quiero ser el único, no el indicado',
  'No puedo prometer ser bueno. Pero prometo estar siempre a tu lado',
  'Si me convierto en un representante de la gente, definitivamente fracasaré, ¿cómo puedo pensar en la gente si lo único que tengo en mente eres tú?',
  'Mira mi jardín, lleno de flores. Mira tus ojos, mi corazón está floreciendo',
  'Promete estar conmigo ahora, mañana y siempre',
  'Desaparecer no solo surge por la distancia. Pero también por deseos que no se hacen realidad',
  'Nunca estarás lejos de mí, donde quiera que vaya tú siempre estás ahí, porque siempre estás en mi corazón, lo que está lejos son solo nuestros cuerpos, no nuestros corazones',
  'Sé en cada mirada que nos obstaculiza la distancia y el tiempo. Pero creo que luego definitivamente estaremos unidos',
  'Extrañarte sin siquiera conocerte es lo mismo que crear una canción que nunca se ha cantado',
  'Hay momentos en que la distancia es siempre una barrera entre tú y yo, pero aún así en mi corazón siempre estamos cerca',
  'Si este corazón no es capaz de contener todo el anhelo, ¿qué puedo hacer sino orar por ti?',
  'Tal vez en este momento sólo pueda contener este anhelo. Hasta que llegue el momento en que pueda encontrarme y liberar este anhelo contigo',
  'A través del turbulento anhelo en mi corazón, a veces realmente necesito tus amorosos abrazos',
  'En la noche fría, ya no recuerdo; cuantas veces pienso en ti también te extraño',
  'Extrañarte es como la lluvia que llega de repente y dura mucho tiempo. E incluso después de que cesa la lluvia, todavía te extraño',
  'Desde que te conocí, quiero seguir aprendiendo, aprender a ser el mejor para ti',
  '¿Sabes la diferencia entre un lápiz y tu cara? Si puedes borrar el lápiz de escribir, pero si tu cara nada podrá borrarlo de mi mente.',
  'No es el Examen Nacional de mañana de lo que tengo que preocuparme, sino la prueba de vida por la que pasé después de que me dejaste',
  'Una cosa acerca de la felicidad en la escuela que me mantiene motivado es poder ver tu sonrisa todos los días',
  '¿Sabes la diferencia entre ir a la escuela e ir a tu casa? Si vas a la escuela, debes traer libros y bolígrafos, pero si vas a tu casa, solo traigo mi corazón y amor',
  'No estoy triste si mañana es lunes, estoy triste si no te veo',
  'Mi momento de amor es perpendicular a tu momento de amor. Haz de nuestro amor un punto de equilibrio perfecto',
  'Estoy dispuesto a participar en una carrera a pie por todo el mundo, siempre que tú estés en la línea de meta',
  'Mi tarea es extrañarte. Más fuerte que las matemáticas, más amplio que la física, más fuerte que la biología',
  'Mi amor por ti es como un metabolismo, que no se detendrá hasta la muerte',
  'Si el jelangkung es como tú, ven a buscarme, te llevaré a casa',
  'Come lo que quiera siempre que esté contigo, incluido comer hígado',
  'El amor es como una sentencia de muerte. Si no te disparan, lo cuelgas',
  'Amarte es como una droga: una vez que intentas ser adicto, no intentas despertar la curiosidad, deja que te haga adicto',
  'Me gusta más picar porque picar es delicioso. Además, tenerte completamente ...',
  'Este mundo nos pertenece sólo a nosotros dos. Todo lo demás es sólo un contrato',
  'Para mí, todos esos días son martes. Martes en el cielo cuando estás cerca ...',
  '¿Y si los dos nos convertimos en una banda de criminales? Yo te robé el corazón y tú me robaste el mío',
  'Eres como el café que tomé esta mañana. Amargo, pero adictivo.',
  'A menudo tengo celos de tu lápiz labial. Él puede besarte todos los días, de la mañana a la noche',
  'Solo escuchar tu nombre puede hacerme sonreír como un tonto',
  'Sé que tu novia no es la única, y como tú no solo yo',
  'Desde que dejé de desearte, me he desmotivado en todo ..',
  'Contigo, enamorarse es el desamor más intencionado',
  'Es muy difícil sentir la felicidad de la vida sin ti a mi lado',
  'A través del turbulento anhelo en mi corazón, a veces realmente necesito tus amorosos abrazos',
  'Si lo sabes, hasta ahora te sigo amando',
  'A veces tengo celos de las cometas ... las cuerdas simplemente se rompen, todavía las persiguen y no quieren que otras personas se apoderen de ellas ...',
  'No sabía qué era el amor, hasta que finalmente te conocí. Pero, en ese momento supe cómo se sentía tener el corazón roto',
  'Perseguir es agotador, pero aún más cansado esperar \ nEsperar a que te des cuenta de mi existencia ...',
  'No dejes de amar solo porque te han herido. Porque no hay arcoíris sin lluvia, no hay amor verdadero sin lágrimas',
  'Tengo un millón de razones para olvidarte, pero nada puede obligarme a dejar de amarte',
  'A veces uno se siente tan estúpido por amar a alguien',
  'Eres el mejor corazón roto del que nunca me arrepiento',
  'No es que no valga la pena esperar, es solo que a menudo da falsas esperanzas',
  'Parte de mí duele, recordarla tan cerca, pero intocable',
  'Lo mejor de amar a alguien es orar en secreto por ellos',
  'Ojalá pudiera deshacerme de este sentimiento tan pronto como te perdí',
  'Por amor nos engañamos a nosotros mismos. Tratar de ser fuertes resulta deshonroso',
  'Piensa en mí como tu casa, si vas ya sabes dónde ir a casa. Quédate si quieres y vete si estás aburrido ...',
  'Estoy confundido, ¿debería estar decepcionado o no? Si estoy decepcionado, ¿quién soy yo para él? \ N \ nSi no estoy decepcionado, pero estoy esperando sus palabras.',
  'Mi anhelo es como una rama que se queda en pie. Aunque no le quedan más hojas para acompañarla, hasta que finalmente se seca, se rompe y muere',
  'Supongo que solo somos dos extraños que ahora tenemos los mismos recuerdos',
  'Haz que te odie aunque sea solo por unos minutos, para que no sea tan difícil olvidarte',
  'Te amo con todo mi corazón, pero compartes tus sentimientos con otras personas',
  'Amarte puede que me rompa, pero de alguna manera dejarte no me arregla',
  'Tú eres el primero y más importante en mi vida. Pero yo soy el segundo después de ti',
  'Si solo podemos encontrarnos en un sueño, quiero dormir para siempre',
  'Verte feliz es mi felicidad, aunque seas feliz sin mí',
  'A veces envidio un objeto. No tiene gusto pero siempre es necesario. A diferencia de mí, que tiene gusto, pero es abandonado e ignorado ...',
  '¿Cómo puedo moverme si solo a ti mi corazón se detiene?',
  'Los recuerdos de ti son como mi hogar. Así que cada vez que mi mente divague, siempre volverá a ti',
  '¿Por qué es útil el tejido? Porque el amor nunca se seca. - Sujiwo Tejo',
  'Si amarte es un error, está bien, déjame seguir estando equivocado',
  'Desde que te conocí, quiero seguir aprendiendo. Aprende a ser el mejor para ti',
  'Algunas personas actúan de forma estúpida solo para verte sonreír. Y él está feliz por eso',
  'No soy una buena persona, pero aprenderé a ser el mejor para ti',
  'No morimos, pero son las heridas las que nos impiden caminar como antes',
  'Tu presencia es como una taza de café que necesito todas las mañanas, lo que puede animarme a estar emocionado por el día',
  'Tengo muchas ganas de darte el mundo. Pero como eso no es posible, entonces te daré lo más importante de mi vida, que es mi mundo',
  'Es mejor cantar con humor pero con dulzura, en lugar de fingir ser romántico pero tener un final trágico',
  'Ben no termina decepcionado, hay que saber cuándo esperar y cuándo parar',
  'Yo, Ki wong Jowo, no entiendo el significado de I Love U',
  'No necesitas ayu y sugih, estoy bastante seguro de que estamos felices y locos',
  'Mi amor por tu equipo se rompe con la cámara, enfócate en tu equipo, pero está borroso',
  'Saben dino kegowo sueña pero no puede ser estúpido',
  'No conozcas a koe 30 dino rasane koyo al mes',
  'Estoy sin ti como un gato que perdió la goma. Ambyar.',
  'Lo quiero, siempre estoy jugando. Supoyo soy iso nemokne kowe lewih hot. Ben Lewih dowo cuando estoy kanggo urip con tu slira.',
  'Nunca supe lo que era opo kui tresno, me acabo de conocer gracias a tu slira',
  'Love aa ka neng moal leungit-leungit sanajan aa geus marry deui.',
  'Tu paciencia es limitada, pero tu amor es ka anjeun henteuaya se epna. ',
  'Kanyaah no se desvanecerá incluso con Bayclean.',
  'Recuerdos asombrosos de estar junto a ti ek luego recordados hasta que los olvidas.',
  'No podré vivir solo, necesito la ayuda de otras personas',
  'Poner aa en neg es como un banquero para cobrar deudas (vamos)',
  'Nuestra paciencia es limitada, pero nuestro amor por ti nunca terminará',
  'Quiero sentir que recopilo todas las palabras de amor que hay en este mundo, y luego pasar por mi a recopilar, para que conozcas mi inmenso sentido del amor por ti',
  'Cálmate, mi amor es como una canción de krispatih; el tiempo no se acabará',
  'No soy la persona perfecta para ti, ni la mejor para ti. Pero seguro, soy la única persona que sigue recordándote',
  'Es suficiente que la red se pierda, tú no',
  'A menudo está hecho para comer hígado. Pero darte cuenta de que todavía estás aquí te vuelve feliz',
  'Mis enemigos son los que también quieren tenerte',
  'Siempre hay muchos, pero si solo quiero a ti, ¿qué?',
  'Mis horas de sueño se arruinaron por el anhelo',
  'Basta con que China esté lejos, nuestro amor no',
  'Lo importante es tu felicidad, yo no soy importante ...',
  'Solo un deseo, amado por ti ...',
  'Estoy sin ti como una ambulancia sin sonido',
  'Es suficiente que la Antártida esté lejos. Entre nosotros',
]
